### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [weijia-cheng/leo-tolstoy_resurrection_louise-maude#1]
chapter-1-3.xhtml
- [x] I noticed that the page scans have quotes around the letter and postscript.
- [x] You are missing semantics and CSS for the postscript. See [SEMOS 7.7.3.5](https://standardebooks.org/manual/1.6.2/7-high-level-structural-patterns#7.7.3.5)

chapter-2-18.xhtml
- [x] There shouldn't be language tags for English words. You can remove the `xml:lang="fr"` from the letter `<blockquote>` and surround the parts within the letter that are in French with `<i xml:lang="fr">`.
- [x] Lint will also tell you to remove `body [xml|lang] i` from the local.css after you make the above change.

local.css
- [x] Instead of using
```
body [xml|lang] [epub|type~="z3998:signature"]{
	font-style: normal;
}
```
to prevent the language tag from italicizing the signature, just add `font-style: normal;` to the original letter CSS. It will look like this:
```
[epub|type~="z3998:sender"],
[epub|type~="z3998:salutation"],
[epub|type~="z3998:signature"]{
	font-style: normal;
	font-variant: small-caps;
}
```
This is really nitpicky stuff. It just keeps letter CSS all together.

**Comment by weijia-cheng** [comment]
Thanks for the review! I have fixed these issues.
